name: PCK.AUTOMIC_JBOSS_V7
source: ae
binaries: 
- object: RESOURCES/PCK.AUTOMIC_JBOSS_V7.PRV.CUSTOM_TYPES
  timestamp: disabled
  resources: 
  - name: DEPLOYMENTTARGET#JBOSS_V7#1
    type: TEXT
    path: ara/types/deploymenttarget/JBoss v7.xml
    version: 1.0.0
  - name: COMPONENT#JBOSS_V7#2
    type: TEXT
    path: ara/types/component/JBoss v7.xml
    version: 1.0.0
- object: RESOURCES/LIBS/PCK.AUTOMIC_JBOSS_V7.PRV.STORE
  resources: 
  - name: JBOSSV7TOOL.JAR
    type: BINARY
    path: tools/jboss-v7-tool/target/jboss-v7-tool.jar
    version: 1.0.0
