//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Datasources complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Datasources">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data-sources" type="{http://www.example.org/JBossV7SnapshotSchema}GeneralDataSources"/>
 *         &lt;element name="xa-data-sources" type="{http://www.example.org/JBossV7SnapshotSchema}XaDataSources"/>
 *         &lt;element name="jdbc-drivers" type="{http://www.example.org/JBossV7SnapshotSchema}JdbcDrivers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Datasources Subsystem" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datasources", propOrder = {
    "dataSources",
    "xaDataSources",
    "jdbcDrivers"
})
public class Datasources {

    @XmlElement(name = "data-sources", required = true)
    protected GeneralDataSources dataSources;
    @XmlElement(name = "xa-data-sources", required = true)
    protected XaDataSources xaDataSources;
    @XmlElement(name = "jdbc-drivers", required = true)
    protected JdbcDrivers jdbcDrivers;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the dataSources property.
     *
     * @return
     *     possible object is
     *     {@link GeneralDataSources }
     *
     */
    public GeneralDataSources getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     *
     * @param value
     *     allowed object is
     *     {@link GeneralDataSources }
     *
     */
    public void setDataSources(GeneralDataSources value) {
        this.dataSources = value;
    }

    /**
     * Gets the value of the xaDataSources property.
     *
     * @return
     *     possible object is
     *     {@link XaDataSources }
     *
     */
    public XaDataSources getXaDataSources() {
        return xaDataSources;
    }

    /**
     * Sets the value of the xaDataSources property.
     *
     * @param value
     *     allowed object is
     *     {@link XaDataSources }
     *
     */
    public void setXaDataSources(XaDataSources value) {
        this.xaDataSources = value;
    }

    /**
     * Gets the value of the jdbcDrivers property.
     *
     * @return
     *     possible object is
     *     {@link JdbcDrivers }
     *
     */
    public JdbcDrivers getJdbcDrivers() {
        return jdbcDrivers;
    }

    /**
     * Sets the value of the jdbcDrivers property.
     *
     * @param value
     *     allowed object is
     *     {@link JdbcDrivers }
     *
     */
    public void setJdbcDrivers(JdbcDrivers value) {
        this.jdbcDrivers = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        if (name == null) {
            return "Datasources Subsystem";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
