//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for EjbDDType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EjbDDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session-beans">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="session-bean" type="{http://www.example.org/JBossV7SnapshotSchema}SessionBeanType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Session Beans" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message-driven-beans">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message-driven-bean" type="{http://www.example.org/JBossV7SnapshotSchema}MessageDrivenBeanType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Message Driven Beans" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entity-beans">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entity-bean" type="{http://www.example.org/JBossV7SnapshotSchema}EntityBeanType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Entity Beans" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="ejb-jar.xml" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EjbDDType", propOrder = {
    "sessionBeans",
    "messageDrivenBeans",
    "entityBeans"
})
public class EjbDDType {

    @XmlElement(name = "session-beans", required = true)
    protected EjbDDType.SessionBeans sessionBeans;
    @XmlElement(name = "message-driven-beans", required = true)
    protected EjbDDType.MessageDrivenBeans messageDrivenBeans;
    @XmlElement(name = "entity-beans", required = true)
    protected EjbDDType.EntityBeans entityBeans;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the sessionBeans property.
     *
     * @return
     *     possible object is
     *     {@link EjbDDType.SessionBeans }
     *
     */
    public EjbDDType.SessionBeans getSessionBeans() {
        return sessionBeans;
    }

    /**
     * Sets the value of the sessionBeans property.
     *
     * @param value
     *     allowed object is
     *     {@link EjbDDType.SessionBeans }
     *
     */
    public void setSessionBeans(EjbDDType.SessionBeans value) {
        this.sessionBeans = value;
    }

    /**
     * Gets the value of the messageDrivenBeans property.
     *
     * @return
     *     possible object is
     *     {@link EjbDDType.MessageDrivenBeans }
     *
     */
    public EjbDDType.MessageDrivenBeans getMessageDrivenBeans() {
        return messageDrivenBeans;
    }

    /**
     * Sets the value of the messageDrivenBeans property.
     *
     * @param value
     *     allowed object is
     *     {@link EjbDDType.MessageDrivenBeans }
     *
     */
    public void setMessageDrivenBeans(EjbDDType.MessageDrivenBeans value) {
        this.messageDrivenBeans = value;
    }

    /**
     * Gets the value of the entityBeans property.
     *
     * @return
     *     possible object is
     *     {@link EjbDDType.EntityBeans }
     *
     */
    public EjbDDType.EntityBeans getEntityBeans() {
        return entityBeans;
    }

    /**
     * Sets the value of the entityBeans property.
     *
     * @param value
     *     allowed object is
     *     {@link EjbDDType.EntityBeans }
     *
     */
    public void setEntityBeans(EjbDDType.EntityBeans value) {
        this.entityBeans = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        if (name == null) {
            return "ejb-jar.xml";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity-bean" type="{http://www.example.org/JBossV7SnapshotSchema}EntityBeanType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Entity Beans" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityBean"
    })
    public static class EntityBeans {

        @XmlElement(name = "entity-bean")
        protected List<EntityBeanType> entityBean;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the entityBean property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entityBean property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntityBean().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntityBeanType }
         *
         *
         */
        public List<EntityBeanType> getEntityBean() {
            if (entityBean == null) {
                entityBean = new ArrayList<EntityBeanType>();
            }
            return this.entityBean;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            if (name == null) {
                return "Entity Beans";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="message-driven-bean" type="{http://www.example.org/JBossV7SnapshotSchema}MessageDrivenBeanType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Message Driven Beans" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageDrivenBean"
    })
    public static class MessageDrivenBeans {

        @XmlElement(name = "message-driven-bean")
        protected List<MessageDrivenBeanType> messageDrivenBean;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the messageDrivenBean property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the messageDrivenBean property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessageDrivenBean().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessageDrivenBeanType }
         *
         *
         */
        public List<MessageDrivenBeanType> getMessageDrivenBean() {
            if (messageDrivenBean == null) {
                messageDrivenBean = new ArrayList<MessageDrivenBeanType>();
            }
            return this.messageDrivenBean;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            if (name == null) {
                return "Message Driven Beans";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="session-bean" type="{http://www.example.org/JBossV7SnapshotSchema}SessionBeanType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Session Beans" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sessionBean"
    })
    public static class SessionBeans {

        @XmlElement(name = "session-bean")
        protected List<SessionBeanType> sessionBean;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the sessionBean property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sessionBean property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSessionBean().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SessionBeanType }
         *
         *
         */
        public List<SessionBeanType> getSessionBean() {
            if (sessionBean == null) {
                sessionBean = new ArrayList<SessionBeanType>();
            }
            return this.sessionBean;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            if (name == null) {
                return "Session Beans";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
