//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for EjbResType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EjbResType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejb-local-refs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ejb-local-ref" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="local-home" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ejb-refs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ejb-ref" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="home" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EjbResType", propOrder = {
    "ejbLocalRefs",
    "ejbRefs"
})
public class EjbResType {

    @XmlElement(name = "ejb-local-refs")
    protected EjbResType.EjbLocalRefs ejbLocalRefs;
    @XmlElement(name = "ejb-refs")
    protected EjbResType.EjbRefs ejbRefs;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the ejbLocalRefs property.
     *
     * @return
     *     possible object is
     *     {@link EjbResType.EjbLocalRefs }
     *
     */
    public EjbResType.EjbLocalRefs getEjbLocalRefs() {
        return ejbLocalRefs;
    }

    /**
     * Sets the value of the ejbLocalRefs property.
     *
     * @param value
     *     allowed object is
     *     {@link EjbResType.EjbLocalRefs }
     *
     */
    public void setEjbLocalRefs(EjbResType.EjbLocalRefs value) {
        this.ejbLocalRefs = value;
    }

    /**
     * Gets the value of the ejbRefs property.
     *
     * @return
     *     possible object is
     *     {@link EjbResType.EjbRefs }
     *
     */
    public EjbResType.EjbRefs getEjbRefs() {
        return ejbRefs;
    }

    /**
     * Sets the value of the ejbRefs property.
     *
     * @param value
     *     allowed object is
     *     {@link EjbResType.EjbRefs }
     *
     */
    public void setEjbRefs(EjbResType.EjbRefs value) {
        this.ejbRefs = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ejb-local-ref" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="local-home" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ejbLocalRef"
    })
    public static class EjbLocalRefs {

        @XmlElement(name = "ejb-local-ref")
        protected List<EjbResType.EjbLocalRefs.EjbLocalRef> ejbLocalRef;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the ejbLocalRef property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ejbLocalRef property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEjbLocalRef().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EjbResType.EjbLocalRefs.EjbLocalRef }
         *
         *
         */
        public List<EjbResType.EjbLocalRefs.EjbLocalRef> getEjbLocalRef() {
            if (ejbLocalRef == null) {
                ejbLocalRef = new ArrayList<EjbResType.EjbLocalRefs.EjbLocalRef>();
            }
            return this.ejbLocalRef;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="local-home" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "ejbRefType",
            "localHome",
            "local",
            "ejbLink"
        })
        public static class EjbLocalRef {

            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "ejb-ref-type", required = true)
            protected String ejbRefType;
            @XmlElement(name = "local-home", required = true)
            protected String localHome;
            @XmlElement(required = true)
            protected String local;
            @XmlElement(name = "ejb-link", required = true)
            protected String ejbLink;
            @XmlAttribute(name = "ejb-ref-name")
            protected String ejbRefName;

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the ejbRefType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbRefType() {
                return ejbRefType;
            }

            /**
             * Sets the value of the ejbRefType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbRefType(String value) {
                this.ejbRefType = value;
            }

            /**
             * Gets the value of the localHome property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLocalHome() {
                return localHome;
            }

            /**
             * Sets the value of the localHome property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLocalHome(String value) {
                this.localHome = value;
            }

            /**
             * Gets the value of the local property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getLocal() {
                return local;
            }

            /**
             * Sets the value of the local property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setLocal(String value) {
                this.local = value;
            }

            /**
             * Gets the value of the ejbLink property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbLink() {
                return ejbLink;
            }

            /**
             * Sets the value of the ejbLink property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbLink(String value) {
                this.ejbLink = value;
            }

            /**
             * Gets the value of the ejbRefName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbRefName() {
                return ejbRefName;
            }

            /**
             * Sets the value of the ejbRefName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbRefName(String value) {
                this.ejbRefName = value;
            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ejb-ref" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="home" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ejbRef"
    })
    public static class EjbRefs {

        @XmlElement(name = "ejb-ref")
        protected List<EjbResType.EjbRefs.EjbRef> ejbRef;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the ejbRef property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ejbRef property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEjbRef().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EjbResType.EjbRefs.EjbRef }
         *
         *
         */
        public List<EjbResType.EjbRefs.EjbRef> getEjbRef() {
            if (ejbRef == null) {
                ejbRef = new ArrayList<EjbResType.EjbRefs.EjbRef>();
            }
            return this.ejbRef;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ejb-ref-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="home" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ejb-link" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="ejb-ref-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "ejbRefType",
            "home",
            "remote",
            "ejbLink"
        })
        public static class EjbRef {

            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "ejb-ref-type", required = true)
            protected String ejbRefType;
            @XmlElement(required = true)
            protected String home;
            @XmlElement(required = true)
            protected String remote;
            @XmlElement(name = "ejb-link", required = true)
            protected String ejbLink;
            @XmlAttribute(name = "ejb-ref-name")
            protected String ejbRefName;

            /**
             * Gets the value of the description property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the ejbRefType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbRefType() {
                return ejbRefType;
            }

            /**
             * Sets the value of the ejbRefType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbRefType(String value) {
                this.ejbRefType = value;
            }

            /**
             * Gets the value of the home property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getHome() {
                return home;
            }

            /**
             * Sets the value of the home property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setHome(String value) {
                this.home = value;
            }

            /**
             * Gets the value of the remote property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getRemote() {
                return remote;
            }

            /**
             * Sets the value of the remote property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setRemote(String value) {
                this.remote = value;
            }

            /**
             * Gets the value of the ejbLink property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbLink() {
                return ejbLink;
            }

            /**
             * Sets the value of the ejbLink property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbLink(String value) {
                this.ejbLink = value;
            }

            /**
             * Gets the value of the ejbRefName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getEjbRefName() {
                return ejbRefName;
            }

            /**
             * Sets the value of the ejbRefName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setEjbRefName(String value) {
                this.ejbRefName = value;
            }

        }

    }

}
