//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Host complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Host">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="master" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="host-state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="running-mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="product-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="release-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="directory-grouping" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="server" type="{http://www.example.org/JBossV7SnapshotSchema}Server" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="interfaces" type="{http://www.example.org/JBossV7SnapshotSchema}Interfaces"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Host", propOrder = {
    "master",
    "hostState",
    "runningMode",
    "productName",
    "productVersion",
    "releaseVersion",
    "directoryGrouping",
    "servers",
    "interfaces"
})
public class Host {

    @XmlElement(required = true)
    protected String master;
    @XmlElement(name = "host-state", required = true)
    protected String hostState;
    @XmlElement(name = "running-mode", required = true)
    protected String runningMode;
    @XmlElement(name = "product-name", required = true)
    protected String productName;
    @XmlElement(name = "product-version", required = true)
    protected String productVersion;
    @XmlElement(name = "release-version", required = true)
    protected String releaseVersion;
    @XmlElement(name = "directory-grouping", required = true)
    protected String directoryGrouping;
    @XmlElement(required = true)
    protected Host.Servers servers;
    @XmlElement(required = true)
    protected Interfaces interfaces;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the master property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMaster() {
        return master;
    }

    /**
     * Sets the value of the master property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMaster(String value) {
        this.master = value;
    }

    /**
     * Gets the value of the hostState property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHostState() {
        return hostState;
    }

    /**
     * Sets the value of the hostState property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHostState(String value) {
        this.hostState = value;
    }

    /**
     * Gets the value of the runningMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRunningMode() {
        return runningMode;
    }

    /**
     * Sets the value of the runningMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRunningMode(String value) {
        this.runningMode = value;
    }

    /**
     * Gets the value of the productName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * Sets the value of the productVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProductVersion(String value) {
        this.productVersion = value;
    }

    /**
     * Gets the value of the releaseVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReleaseVersion() {
        return releaseVersion;
    }

    /**
     * Sets the value of the releaseVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReleaseVersion(String value) {
        this.releaseVersion = value;
    }

    /**
     * Gets the value of the directoryGrouping property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDirectoryGrouping() {
        return directoryGrouping;
    }

    /**
     * Sets the value of the directoryGrouping property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDirectoryGrouping(String value) {
        this.directoryGrouping = value;
    }

    /**
     * Gets the value of the servers property.
     *
     * @return
     *     possible object is
     *     {@link Host.Servers }
     *
     */
    public Host.Servers getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     *
     * @param value
     *     allowed object is
     *     {@link Host.Servers }
     *
     */
    public void setServers(Host.Servers value) {
        this.servers = value;
    }

    /**
     * Gets the value of the interfaces property.
     *
     * @return
     *     possible object is
     *     {@link Interfaces }
     *
     */
    public Interfaces getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     *
     * @param value
     *     allowed object is
     *     {@link Interfaces }
     *
     */
    public void setInterfaces(Interfaces value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="server" type="{http://www.example.org/JBossV7SnapshotSchema}Server" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "server"
    })
    public static class Servers {

        @XmlElement(nillable = true)
        protected List<Server> server;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the server property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the server property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServer().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Server }
         *
         *
         */
        public List<Server> getServer() {
            if (server == null) {
                server = new ArrayList<Server>();
            }
            return this.server;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
