//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for JdbcDriver complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="JdbcDriver">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="driver-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driver-module-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driver-class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driver-major-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="driver-minor-version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jdbc-compliant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JdbcDriver", propOrder = {
    "driverName",
    "driverModuleName",
    "driverClassName",
    "driverMajorVersion",
    "driverMinorVersion",
    "jdbcCompliant"
})
public class JdbcDriver {

    @XmlElement(name = "driver-name", required = true)
    protected String driverName;
    @XmlElement(name = "driver-module-name", required = true)
    protected String driverModuleName;
    @XmlElement(name = "driver-class-name", required = true)
    protected String driverClassName;
    @XmlElement(name = "driver-major-version", required = true)
    protected String driverMajorVersion;
    @XmlElement(name = "driver-minor-version", required = true)
    protected String driverMinorVersion;
    @XmlElement(name = "jdbc-compliant", required = true)
    protected String jdbcCompliant;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the driverName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverModuleName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDriverModuleName() {
        return driverModuleName;
    }

    /**
     * Sets the value of the driverModuleName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDriverModuleName(String value) {
        this.driverModuleName = value;
    }

    /**
     * Gets the value of the driverClassName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDriverClassName() {
        return driverClassName;
    }

    /**
     * Sets the value of the driverClassName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDriverClassName(String value) {
        this.driverClassName = value;
    }

    /**
     * Gets the value of the driverMajorVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDriverMajorVersion() {
        return driverMajorVersion;
    }

    /**
     * Sets the value of the driverMajorVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDriverMajorVersion(String value) {
        this.driverMajorVersion = value;
    }

    /**
     * Gets the value of the driverMinorVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDriverMinorVersion() {
        return driverMinorVersion;
    }

    /**
     * Sets the value of the driverMinorVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDriverMinorVersion(String value) {
        this.driverMinorVersion = value;
    }

    /**
     * Gets the value of the jdbcCompliant property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJdbcCompliant() {
        return jdbcCompliant;
    }

    /**
     * Sets the value of the jdbcCompliant property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJdbcCompliant(String value) {
        this.jdbcCompliant = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
