//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Profile complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasources" type="{http://www.example.org/JBossV7SnapshotSchema}Datasources"/>
 *         &lt;element name="messaging" type="{http://www.example.org/JBossV7SnapshotSchema}Messaging"/>
 *         &lt;element name="subsystems" type="{http://www.example.org/JBossV7SnapshotSchema}SubSystems"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Profile", propOrder = {
    "datasources",
    "messaging",
    "subsystems"
})
public class Profile {

    @XmlElement(required = true)
    protected Datasources datasources;
    @XmlElement(required = true)
    protected Messaging messaging;
    @XmlElement(required = true)
    protected SubSystems subsystems;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the datasources property.
     *
     * @return
     *     possible object is
     *     {@link Datasources }
     *
     */
    public Datasources getDatasources() {
        return datasources;
    }

    /**
     * Sets the value of the datasources property.
     *
     * @param value
     *     allowed object is
     *     {@link Datasources }
     *
     */
    public void setDatasources(Datasources value) {
        this.datasources = value;
    }

    /**
     * Gets the value of the messaging property.
     *
     * @return
     *     possible object is
     *     {@link Messaging }
     *
     */
    public Messaging getMessaging() {
        return messaging;
    }

    /**
     * Sets the value of the messaging property.
     *
     * @param value
     *     allowed object is
     *     {@link Messaging }
     *
     */
    public void setMessaging(Messaging value) {
        this.messaging = value;
    }

    /**
     * Gets the value of the subsystems property.
     *
     * @return
     *     possible object is
     *     {@link SubSystems }
     *
     */
    public SubSystems getSubsystems() {
        return subsystems;
    }

    /**
     * Sets the value of the subsystems property.
     *
     * @param value
     *     allowed object is
     *     {@link SubSystems }
     *
     */
    public void setSubsystems(SubSystems value) {
        this.subsystems = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
