//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ResourceAdapterType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ResourceAdapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connection-definitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="connection-definition" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="jndi-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="config-properties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="config-property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="config-property-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="config-property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="config-property-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceAdapterType", propOrder = {
    "connectionDefinitions",
    "configProperties"
})
public class ResourceAdapterType {

    @XmlElement(name = "connection-definitions", required = true)
    protected ResourceAdapterType.ConnectionDefinitions connectionDefinitions;
    @XmlElement(name = "config-properties", required = true)
    protected ResourceAdapterType.ConfigProperties configProperties;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the connectionDefinitions property.
     *
     * @return
     *     possible object is
     *     {@link ResourceAdapterType.ConnectionDefinitions }
     *
     */
    public ResourceAdapterType.ConnectionDefinitions getConnectionDefinitions() {
        return connectionDefinitions;
    }

    /**
     * Sets the value of the connectionDefinitions property.
     *
     * @param value
     *     allowed object is
     *     {@link ResourceAdapterType.ConnectionDefinitions }
     *
     */
    public void setConnectionDefinitions(ResourceAdapterType.ConnectionDefinitions value) {
        this.connectionDefinitions = value;
    }

    /**
     * Gets the value of the configProperties property.
     *
     * @return
     *     possible object is
     *     {@link ResourceAdapterType.ConfigProperties }
     *
     */
    public ResourceAdapterType.ConfigProperties getConfigProperties() {
        return configProperties;
    }

    /**
     * Sets the value of the configProperties property.
     *
     * @param value
     *     allowed object is
     *     {@link ResourceAdapterType.ConfigProperties }
     *
     */
    public void setConfigProperties(ResourceAdapterType.ConfigProperties value) {
        this.configProperties = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="config-property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="config-property-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="config-property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="config-property-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "configProperty"
    })
    public static class ConfigProperties {

        @XmlElement(name = "config-property", nillable = true)
        protected List<ResourceAdapterType.ConfigProperties.ConfigProperty> configProperty;

        /**
         * Gets the value of the configProperty property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the configProperty property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConfigProperty().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResourceAdapterType.ConfigProperties.ConfigProperty }
         *
         *
         */
        public List<ResourceAdapterType.ConfigProperties.ConfigProperty> getConfigProperty() {
            if (configProperty == null) {
                configProperty = new ArrayList<ResourceAdapterType.ConfigProperties.ConfigProperty>();
            }
            return this.configProperty;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="config-property-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="config-property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="config-property-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "configPropertyType",
            "configPropertyValue"
        })
        public static class ConfigProperty {

            @XmlElement(name = "config-property-type", required = true)
            protected String configPropertyType;
            @XmlElement(name = "config-property-value", required = true)
            protected String configPropertyValue;
            @XmlAttribute(name = "config-property-name")
            protected String configPropertyName;

            /**
             * Gets the value of the configPropertyType property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getConfigPropertyType() {
                return configPropertyType;
            }

            /**
             * Sets the value of the configPropertyType property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setConfigPropertyType(String value) {
                this.configPropertyType = value;
            }

            /**
             * Gets the value of the configPropertyValue property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getConfigPropertyValue() {
                return configPropertyValue;
            }

            /**
             * Sets the value of the configPropertyValue property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setConfigPropertyValue(String value) {
                this.configPropertyValue = value;
            }

            /**
             * Gets the value of the configPropertyName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getConfigPropertyName() {
                return configPropertyName;
            }

            /**
             * Sets the value of the configPropertyName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setConfigPropertyName(String value) {
                this.configPropertyName = value;
            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="connection-definition" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="jndi-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connectionDefinition"
    })
    public static class ConnectionDefinitions {

        @XmlElement(name = "connection-definition", nillable = true)
        protected List<ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition> connectionDefinition;

        /**
         * Gets the value of the connectionDefinition property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the connectionDefinition property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnectionDefinition().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition }
         *
         *
         */
        public List<ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition> getConnectionDefinition() {
            if (connectionDefinition == null) {
                connectionDefinition = new ArrayList<ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition>();
            }
            return this.connectionDefinition;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="jndi-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "jndiName"
        })
        public static class ConnectionDefinition {

            @XmlElement(name = "jndi-name", required = true)
            protected String jndiName;
            @XmlAttribute(name = "class-name")
            protected String className;

            /**
             * Gets the value of the jndiName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getJndiName() {
                return jndiName;
            }

            /**
             * Sets the value of the jndiName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setJndiName(String value) {
                this.jndiName = value;
            }

            /**
             * Gets the value of the className property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getClassName() {
                return className;
            }

            /**
             * Sets the value of the className property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setClassName(String value) {
                this.className = value;
            }

        }

    }

}
