//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Server complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Server">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="server-state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="running-mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auto-start" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="socket-binding-port-offset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="socket-binding-group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Server", propOrder = {
    "serverState",
    "runningMode",
    "autoStart",
    "group",
    "socketBindingPortOffset",
    "socketBindingGroup"
})
public class Server {

    @XmlElement(name = "server-state", required = true)
    protected String serverState;
    @XmlElement(name = "running-mode", required = true)
    protected String runningMode;
    @XmlElement(name = "auto-start", required = true)
    protected String autoStart;
    @XmlElement(required = true)
    protected String group;
    @XmlElement(name = "socket-binding-port-offset", required = true)
    protected String socketBindingPortOffset;
    @XmlElement(name = "socket-binding-group", required = true)
    protected String socketBindingGroup;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the serverState property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getServerState() {
        return serverState;
    }

    /**
     * Sets the value of the serverState property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setServerState(String value) {
        this.serverState = value;
    }

    /**
     * Gets the value of the runningMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRunningMode() {
        return runningMode;
    }

    /**
     * Sets the value of the runningMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRunningMode(String value) {
        this.runningMode = value;
    }

    /**
     * Gets the value of the autoStart property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAutoStart() {
        return autoStart;
    }

    /**
     * Sets the value of the autoStart property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAutoStart(String value) {
        this.autoStart = value;
    }

    /**
     * Gets the value of the group property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the socketBindingPortOffset property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSocketBindingPortOffset() {
        return socketBindingPortOffset;
    }

    /**
     * Sets the value of the socketBindingPortOffset property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSocketBindingPortOffset(String value) {
        this.socketBindingPortOffset = value;
    }

    /**
     * Gets the value of the socketBindingGroup property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSocketBindingGroup() {
        return socketBindingGroup;
    }

    /**
     * Sets the value of the socketBindingGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSocketBindingGroup(String value) {
        this.socketBindingGroup = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
