//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.12.04 at 03:31:00 PM ICT
//

package com.uc4.ara.feature.jbossv7.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for StandaloneServerSnapshot complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StandaloneServerSnapshot">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/JBossV7SnapshotSchema}ServerSnapshotType">
 *       &lt;sequence>
 *         &lt;element name="server-info" type="{http://www.example.org/JBossV7SnapshotSchema}StandaloneServerInfo"/>
 *         &lt;element name="system-properties" type="{http://www.example.org/JBossV7SnapshotSchema}SystemProperties"/>
 *         &lt;element name="deployments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deployment" type="{http://www.example.org/JBossV7SnapshotSchema}StandaloneDeployment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Deployments" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datasources" type="{http://www.example.org/JBossV7SnapshotSchema}Datasources"/>
 *         &lt;element name="messaging" type="{http://www.example.org/JBossV7SnapshotSchema}Messaging"/>
 *         &lt;element name="subsystems" type="{http://www.example.org/JBossV7SnapshotSchema}SubSystems"/>
 *         &lt;element name="socket-binding-groups" type="{http://www.example.org/JBossV7SnapshotSchema}SocketBindingGroups"/>
 *         &lt;element name="interfaces" type="{http://www.example.org/JBossV7SnapshotSchema}Interfaces"/>
 *         &lt;element name="extensions" type="{http://www.example.org/JBossV7SnapshotSchema}Extensions"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandaloneServerSnapshot", propOrder = {
    "serverInfo",
    "systemProperties",
    "deployments",
    "datasources",
    "messaging",
    "subsystems",
    "socketBindingGroups",
    "interfaces",
    "extensions"
})
public class StandaloneServerSnapshot
    extends ServerSnapshotType
{

    @XmlElement(name = "server-info", required = true)
    protected StandaloneServerInfo serverInfo;
    @XmlElement(name = "system-properties", required = true)
    protected SystemProperties systemProperties;
    @XmlElement(required = true)
    protected StandaloneServerSnapshot.Deployments deployments;
    @XmlElement(required = true)
    protected Datasources datasources;
    @XmlElement(required = true)
    protected Messaging messaging;
    @XmlElement(required = true)
    protected SubSystems subsystems;
    @XmlElement(name = "socket-binding-groups", required = true)
    protected SocketBindingGroups socketBindingGroups;
    @XmlElement(required = true)
    protected Interfaces interfaces;
    @XmlElement(required = true)
    protected Extensions extensions;

    /**
     * Gets the value of the serverInfo property.
     *
     * @return
     *     possible object is
     *     {@link StandaloneServerInfo }
     *
     */
    public StandaloneServerInfo getServerInfo() {
        return serverInfo;
    }

    /**
     * Sets the value of the serverInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link StandaloneServerInfo }
     *
     */
    public void setServerInfo(StandaloneServerInfo value) {
        this.serverInfo = value;
    }

    /**
     * Gets the value of the systemProperties property.
     *
     * @return
     *     possible object is
     *     {@link SystemProperties }
     *
     */
    public SystemProperties getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     *
     * @param value
     *     allowed object is
     *     {@link SystemProperties }
     *
     */
    public void setSystemProperties(SystemProperties value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the deployments property.
     *
     * @return
     *     possible object is
     *     {@link StandaloneServerSnapshot.Deployments }
     *
     */
    public StandaloneServerSnapshot.Deployments getDeployments() {
        return deployments;
    }

    /**
     * Sets the value of the deployments property.
     *
     * @param value
     *     allowed object is
     *     {@link StandaloneServerSnapshot.Deployments }
     *
     */
    public void setDeployments(StandaloneServerSnapshot.Deployments value) {
        this.deployments = value;
    }

    /**
     * Gets the value of the datasources property.
     *
     * @return
     *     possible object is
     *     {@link Datasources }
     *
     */
    public Datasources getDatasources() {
        return datasources;
    }

    /**
     * Sets the value of the datasources property.
     *
     * @param value
     *     allowed object is
     *     {@link Datasources }
     *
     */
    public void setDatasources(Datasources value) {
        this.datasources = value;
    }

    /**
     * Gets the value of the messaging property.
     *
     * @return
     *     possible object is
     *     {@link Messaging }
     *
     */
    public Messaging getMessaging() {
        return messaging;
    }

    /**
     * Sets the value of the messaging property.
     *
     * @param value
     *     allowed object is
     *     {@link Messaging }
     *
     */
    public void setMessaging(Messaging value) {
        this.messaging = value;
    }

    /**
     * Gets the value of the subsystems property.
     *
     * @return
     *     possible object is
     *     {@link SubSystems }
     *
     */
    public SubSystems getSubsystems() {
        return subsystems;
    }

    /**
     * Sets the value of the subsystems property.
     *
     * @param value
     *     allowed object is
     *     {@link SubSystems }
     *
     */
    public void setSubsystems(SubSystems value) {
        this.subsystems = value;
    }

    /**
     * Gets the value of the socketBindingGroups property.
     *
     * @return
     *     possible object is
     *     {@link SocketBindingGroups }
     *
     */
    public SocketBindingGroups getSocketBindingGroups() {
        return socketBindingGroups;
    }

    /**
     * Sets the value of the socketBindingGroups property.
     *
     * @param value
     *     allowed object is
     *     {@link SocketBindingGroups }
     *
     */
    public void setSocketBindingGroups(SocketBindingGroups value) {
        this.socketBindingGroups = value;
    }

    /**
     * Gets the value of the interfaces property.
     *
     * @return
     *     possible object is
     *     {@link Interfaces }
     *
     */
    public Interfaces getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     *
     * @param value
     *     allowed object is
     *     {@link Interfaces }
     *
     */
    public void setInterfaces(Interfaces value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return
     *     possible object is
     *     {@link Extensions }
     *
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="deployment" type="{http://www.example.org/JBossV7SnapshotSchema}StandaloneDeployment" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Deployments" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deployment"
    })
    public static class Deployments {

        @XmlElement(nillable = true)
        protected List<StandaloneDeployment> deployment;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the deployment property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deployment property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeployment().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StandaloneDeployment }
         *
         *
         */
        public List<StandaloneDeployment> getDeployment() {
            if (deployment == null) {
                deployment = new ArrayList<StandaloneDeployment>();
            }
            return this.deployment;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            if (name == null) {
                return "Deployments";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
