//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="application-runtime" type="{http://www.example.org/JBossV6SnapshotSchema}ApplicationRuntimeType"/>
 *         &lt;element name="deployment-descriptors" type="{http://www.example.org/JBossV6SnapshotSchema}DeploymentDescriptorsType"/>
 *         &lt;element name="sub-deployments" type="{http://www.example.org/JBossV6SnapshotSchema}SubDeploymentType"/>
 *         &lt;element name="sub-systems" type="{http://www.example.org/JBossV6SnapshotSchema}SubsystemType"/>
 *         &lt;element name="other-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
 *         &lt;element name="class-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Application" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationType", propOrder = {
    "applicationRuntime",
    "deploymentDescriptors",
    "subDeployments",
    "subSystems",
    "otherFiles",
    "classFiles"
})
public class ApplicationType {

    @XmlElement(name = "application-runtime", required = true)
    protected ApplicationRuntimeType applicationRuntime;
    @XmlElement(name = "deployment-descriptors", required = true)
    protected DeploymentDescriptorsType deploymentDescriptors;
    @XmlElement(name = "sub-deployments", required = true)
    protected SubDeploymentType subDeployments;
    @XmlElement(name = "sub-systems", required = true)
    protected SubsystemType subSystems;
    @XmlElement(name = "other-files", required = true)
    protected FileGroupType otherFiles;
    @XmlElement(name = "class-files", required = true)
    protected FileGroupType classFiles;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the applicationRuntime property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationRuntimeType }
     *     
     */
    public ApplicationRuntimeType getApplicationRuntime() {
        return applicationRuntime;
    }

    /**
     * Sets the value of the applicationRuntime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationRuntimeType }
     *     
     */
    public void setApplicationRuntime(ApplicationRuntimeType value) {
        this.applicationRuntime = value;
    }

    /**
     * Gets the value of the deploymentDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link DeploymentDescriptorsType }
     *     
     */
    public DeploymentDescriptorsType getDeploymentDescriptors() {
        return deploymentDescriptors;
    }

    /**
     * Sets the value of the deploymentDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeploymentDescriptorsType }
     *     
     */
    public void setDeploymentDescriptors(DeploymentDescriptorsType value) {
        this.deploymentDescriptors = value;
    }

    /**
     * Gets the value of the subDeployments property.
     * 
     * @return
     *     possible object is
     *     {@link SubDeploymentType }
     *     
     */
    public SubDeploymentType getSubDeployments() {
        return subDeployments;
    }

    /**
     * Sets the value of the subDeployments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubDeploymentType }
     *     
     */
    public void setSubDeployments(SubDeploymentType value) {
        this.subDeployments = value;
    }

    /**
     * Gets the value of the subSystems property.
     * 
     * @return
     *     possible object is
     *     {@link SubsystemType }
     *     
     */
    public SubsystemType getSubSystems() {
        return subSystems;
    }

    /**
     * Sets the value of the subSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsystemType }
     *     
     */
    public void setSubSystems(SubsystemType value) {
        this.subSystems = value;
    }

    /**
     * Gets the value of the otherFiles property.
     * 
     * @return
     *     possible object is
     *     {@link FileGroupType }
     *     
     */
    public FileGroupType getOtherFiles() {
        return otherFiles;
    }

    /**
     * Sets the value of the otherFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileGroupType }
     *     
     */
    public void setOtherFiles(FileGroupType value) {
        this.otherFiles = value;
    }

    /**
     * Gets the value of the classFiles property.
     * 
     * @return
     *     possible object is
     *     {@link FileGroupType }
     *     
     */
    public FileGroupType getClassFiles() {
        return classFiles;
    }

    /**
     * Sets the value of the classFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileGroupType }
     *     
     */
    public void setClassFiles(FileGroupType value) {
        this.classFiles = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Application";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
