//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for DomainServerSnapshot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomainServerSnapshot">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/JBossV6SnapshotSchema}ServerSnapshotType">
 *       &lt;sequence>
 *         &lt;element name="server-info" type="{http://www.example.org/JBossV6SnapshotSchema}DomainServerInfo"/>
 *         &lt;element name="system-properties" type="{http://www.example.org/JBossV6SnapshotSchema}SystemProperties"/>
 *         &lt;element name="deployments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deployment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="runtime-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Deployments" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hosts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="host" type="{http://www.example.org/JBossV6SnapshotSchema}Host" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Hosts" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="server-groups">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="server-group" type="{http://www.example.org/JBossV6SnapshotSchema}ServerGroup" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Server Groups" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="profiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="profile" type="{http://www.example.org/JBossV6SnapshotSchema}Profile" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Profiles" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="socket-binding-groups" type="{http://www.example.org/JBossV6SnapshotSchema}SocketBindingGroups"/>
 *         &lt;element name="extensions" type="{http://www.example.org/JBossV6SnapshotSchema}Extensions"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainServerSnapshot", propOrder = {
    "serverInfo",
    "systemProperties",
    "deployments",
    "hosts",
    "serverGroups",
    "profiles",
    "socketBindingGroups",
    "extensions"
})
public class DomainServerSnapshot
    extends ServerSnapshotType
{

    @XmlElement(name = "server-info", required = true)
    protected DomainServerInfo serverInfo;
    @XmlElement(name = "system-properties", required = true)
    protected SystemProperties systemProperties;
    @XmlElement(required = true)
    protected DomainServerSnapshot.Deployments deployments;
    @XmlElement(required = true)
    protected DomainServerSnapshot.Hosts hosts;
    @XmlElement(name = "server-groups", required = true)
    protected DomainServerSnapshot.ServerGroups serverGroups;
    @XmlElement(required = true)
    protected DomainServerSnapshot.Profiles profiles;
    @XmlElement(name = "socket-binding-groups", required = true)
    protected SocketBindingGroups socketBindingGroups;
    @XmlElement(required = true)
    protected Extensions extensions;

    /**
     * Gets the value of the serverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DomainServerInfo }
     *     
     */
    public DomainServerInfo getServerInfo() {
        return serverInfo;
    }

    /**
     * Sets the value of the serverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainServerInfo }
     *     
     */
    public void setServerInfo(DomainServerInfo value) {
        this.serverInfo = value;
    }

    /**
     * Gets the value of the systemProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SystemProperties }
     *     
     */
    public SystemProperties getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemProperties }
     *     
     */
    public void setSystemProperties(SystemProperties value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the deployments property.
     * 
     * @return
     *     possible object is
     *     {@link DomainServerSnapshot.Deployments }
     *     
     */
    public DomainServerSnapshot.Deployments getDeployments() {
        return deployments;
    }

    /**
     * Sets the value of the deployments property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainServerSnapshot.Deployments }
     *     
     */
    public void setDeployments(DomainServerSnapshot.Deployments value) {
        this.deployments = value;
    }

    /**
     * Gets the value of the hosts property.
     * 
     * @return
     *     possible object is
     *     {@link DomainServerSnapshot.Hosts }
     *     
     */
    public DomainServerSnapshot.Hosts getHosts() {
        return hosts;
    }

    /**
     * Sets the value of the hosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainServerSnapshot.Hosts }
     *     
     */
    public void setHosts(DomainServerSnapshot.Hosts value) {
        this.hosts = value;
    }

    /**
     * Gets the value of the serverGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DomainServerSnapshot.ServerGroups }
     *     
     */
    public DomainServerSnapshot.ServerGroups getServerGroups() {
        return serverGroups;
    }

    /**
     * Sets the value of the serverGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainServerSnapshot.ServerGroups }
     *     
     */
    public void setServerGroups(DomainServerSnapshot.ServerGroups value) {
        this.serverGroups = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link DomainServerSnapshot.Profiles }
     *     
     */
    public DomainServerSnapshot.Profiles getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainServerSnapshot.Profiles }
     *     
     */
    public void setProfiles(DomainServerSnapshot.Profiles value) {
        this.profiles = value;
    }

    /**
     * Gets the value of the socketBindingGroups property.
     * 
     * @return
     *     possible object is
     *     {@link SocketBindingGroups }
     *     
     */
    public SocketBindingGroups getSocketBindingGroups() {
        return socketBindingGroups;
    }

    /**
     * Sets the value of the socketBindingGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketBindingGroups }
     *     
     */
    public void setSocketBindingGroups(SocketBindingGroups value) {
        this.socketBindingGroups = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="deployment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="runtime-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Deployments" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deployment"
    })
    public static class Deployments {

        @XmlElement(nillable = true)
        protected List<DomainServerSnapshot.Deployments.Deployment> deployment;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the deployment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deployment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeployment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DomainServerSnapshot.Deployments.Deployment }
         * 
         * 
         */
        public List<DomainServerSnapshot.Deployments.Deployment> getDeployment() {
            if (deployment == null) {
                deployment = new ArrayList<DomainServerSnapshot.Deployments.Deployment>();
            }
            return this.deployment;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "Deployments";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="runtime-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "runtimeName"
        })
        public static class Deployment {

            @XmlElement(name = "runtime-name", required = true)
            protected String runtimeName;
            @XmlAttribute
            protected String name;

            /**
             * Gets the value of the runtimeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRuntimeName() {
                return runtimeName;
            }

            /**
             * Sets the value of the runtimeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRuntimeName(String value) {
                this.runtimeName = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="host" type="{http://www.example.org/JBossV6SnapshotSchema}Host" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Hosts" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "host"
    })
    public static class Hosts {

        @XmlElement(nillable = true)
        protected List<Host> host;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the host property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the host property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHost().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Host }
         * 
         * 
         */
        public List<Host> getHost() {
            if (host == null) {
                host = new ArrayList<Host>();
            }
            return this.host;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "Hosts";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="profile" type="{http://www.example.org/JBossV6SnapshotSchema}Profile" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Profiles" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "profile"
    })
    public static class Profiles {

        @XmlElement(nillable = true)
        protected List<Profile> profile;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the profile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the profile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Profile }
         * 
         * 
         */
        public List<Profile> getProfile() {
            if (profile == null) {
                profile = new ArrayList<Profile>();
            }
            return this.profile;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "Profiles";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="server-group" type="{http://www.example.org/JBossV6SnapshotSchema}ServerGroup" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="Server Groups" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serverGroup"
    })
    public static class ServerGroups {

        @XmlElement(name = "server-group", nillable = true)
        protected List<ServerGroup> serverGroup;
        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String name;

        /**
         * Gets the value of the serverGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the serverGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServerGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServerGroup }
         * 
         * 
         */
        public List<ServerGroup> getServerGroup() {
            if (serverGroup == null) {
                serverGroup = new ArrayList<ServerGroup>();
            }
            return this.serverGroup;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "Server Groups";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
