//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ejb3SubsystemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ejb3SubsystemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bean" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="security-domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="component-class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="declared-roles" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-available-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-create-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-current-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-max-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pool-remove-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="run-as-role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="timers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="invocations" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="bean-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ejb3SubsystemType", propOrder = {
    "bean"
})
public class Ejb3SubsystemType {

    protected List<Ejb3SubsystemType.Bean> bean;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the bean property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bean property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBean().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ejb3SubsystemType.Bean }
     * 
     * 
     */
    public List<Ejb3SubsystemType.Bean> getBean() {
        if (bean == null) {
            bean = new ArrayList<Ejb3SubsystemType.Bean>();
        }
        return this.bean;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="security-domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="component-class-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="declared-roles" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-available-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-create-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-current-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-max-size" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pool-remove-count" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="run-as-role" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="timers" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="invocations" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="bean-type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "securityDomain",
        "componentClassName",
        "declaredRoles",
        "poolAvailableCount",
        "poolCreateCount",
        "poolCurrentSize",
        "poolMaxSize",
        "poolName",
        "poolRemoveCount",
        "runAsRole",
        "timers",
        "invocations"
    })
    public static class Bean {

        @XmlElement(name = "security-domain", required = true)
        protected String securityDomain;
        @XmlElement(name = "component-class-name", required = true)
        protected String componentClassName;
        @XmlElement(name = "declared-roles", required = true)
        protected String declaredRoles;
        @XmlElement(name = "pool-available-count", required = true)
        protected String poolAvailableCount;
        @XmlElement(name = "pool-create-count", required = true)
        protected String poolCreateCount;
        @XmlElement(name = "pool-current-size", required = true)
        protected String poolCurrentSize;
        @XmlElement(name = "pool-max-size", required = true)
        protected String poolMaxSize;
        @XmlElement(name = "pool-name", required = true)
        protected String poolName;
        @XmlElement(name = "pool-remove-count", required = true)
        protected String poolRemoveCount;
        @XmlElement(name = "run-as-role", required = true)
        protected String runAsRole;
        @XmlElement(required = true)
        protected String timers;
        @XmlElement(required = true)
        protected String invocations;
        @XmlAttribute(name = "bean-type")
        protected String beanType;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the securityDomain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecurityDomain() {
            return securityDomain;
        }

        /**
         * Sets the value of the securityDomain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecurityDomain(String value) {
            this.securityDomain = value;
        }

        /**
         * Gets the value of the componentClassName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComponentClassName() {
            return componentClassName;
        }

        /**
         * Sets the value of the componentClassName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComponentClassName(String value) {
            this.componentClassName = value;
        }

        /**
         * Gets the value of the declaredRoles property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeclaredRoles() {
            return declaredRoles;
        }

        /**
         * Sets the value of the declaredRoles property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeclaredRoles(String value) {
            this.declaredRoles = value;
        }

        /**
         * Gets the value of the poolAvailableCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolAvailableCount() {
            return poolAvailableCount;
        }

        /**
         * Sets the value of the poolAvailableCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolAvailableCount(String value) {
            this.poolAvailableCount = value;
        }

        /**
         * Gets the value of the poolCreateCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolCreateCount() {
            return poolCreateCount;
        }

        /**
         * Sets the value of the poolCreateCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolCreateCount(String value) {
            this.poolCreateCount = value;
        }

        /**
         * Gets the value of the poolCurrentSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolCurrentSize() {
            return poolCurrentSize;
        }

        /**
         * Sets the value of the poolCurrentSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolCurrentSize(String value) {
            this.poolCurrentSize = value;
        }

        /**
         * Gets the value of the poolMaxSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolMaxSize() {
            return poolMaxSize;
        }

        /**
         * Sets the value of the poolMaxSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolMaxSize(String value) {
            this.poolMaxSize = value;
        }

        /**
         * Gets the value of the poolName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolName() {
            return poolName;
        }

        /**
         * Sets the value of the poolName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolName(String value) {
            this.poolName = value;
        }

        /**
         * Gets the value of the poolRemoveCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoolRemoveCount() {
            return poolRemoveCount;
        }

        /**
         * Sets the value of the poolRemoveCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoolRemoveCount(String value) {
            this.poolRemoveCount = value;
        }

        /**
         * Gets the value of the runAsRole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRunAsRole() {
            return runAsRole;
        }

        /**
         * Sets the value of the runAsRole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRunAsRole(String value) {
            this.runAsRole = value;
        }

        /**
         * Gets the value of the timers property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimers() {
            return timers;
        }

        /**
         * Sets the value of the timers property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimers(String value) {
            this.timers = value;
        }

        /**
         * Gets the value of the invocations property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvocations() {
            return invocations;
        }

        /**
         * Sets the value of the invocations property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvocations(String value) {
            this.invocations = value;
        }

        /**
         * Gets the value of the beanType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeanType() {
            return beanType;
        }

        /**
         * Sets the value of the beanType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeanType(String value) {
            this.beanType = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
