//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Messaging complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Messaging">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hornetq-server" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="clustered" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jmx-domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="management-address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="jms-queues">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="jms-queue" type="{http://www.example.org/JBossV6SnapshotSchema}JmsQueue" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="jms-topics">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="jms-topic" type="{http://www.example.org/JBossV6SnapshotSchema}JmsTopic" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Messaging Subsystem" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Messaging", propOrder = {
    "hornetqServer"
})
public class Messaging {

    @XmlElement(name = "hornetq-server", nillable = true)
    protected List<Messaging.HornetqServer> hornetqServer;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the hornetqServer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hornetqServer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHornetqServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Messaging.HornetqServer }
     * 
     * 
     */
    public List<Messaging.HornetqServer> getHornetqServer() {
        if (hornetqServer == null) {
            hornetqServer = new ArrayList<Messaging.HornetqServer>();
        }
        return this.hornetqServer;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Messaging Subsystem";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="clustered" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jmx-domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="management-address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="jms-queues">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="jms-queue" type="{http://www.example.org/JBossV6SnapshotSchema}JmsQueue" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="jms-topics">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="jms-topic" type="{http://www.example.org/JBossV6SnapshotSchema}JmsTopic" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clustered",
        "jmxDomain",
        "version",
        "managementAddress",
        "jmsQueues",
        "jmsTopics"
    })
    public static class HornetqServer {

        @XmlElement(required = true)
        protected String clustered;
        @XmlElement(name = "jmx-domain", required = true)
        protected String jmxDomain;
        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "management-address", required = true)
        protected String managementAddress;
        @XmlElement(name = "jms-queues", required = true)
        protected Messaging.HornetqServer.JmsQueues jmsQueues;
        @XmlElement(name = "jms-topics", required = true)
        protected Messaging.HornetqServer.JmsTopics jmsTopics;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the clustered property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClustered() {
            return clustered;
        }

        /**
         * Sets the value of the clustered property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClustered(String value) {
            this.clustered = value;
        }

        /**
         * Gets the value of the jmxDomain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJmxDomain() {
            return jmxDomain;
        }

        /**
         * Sets the value of the jmxDomain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJmxDomain(String value) {
            this.jmxDomain = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the managementAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManagementAddress() {
            return managementAddress;
        }

        /**
         * Sets the value of the managementAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManagementAddress(String value) {
            this.managementAddress = value;
        }

        /**
         * Gets the value of the jmsQueues property.
         * 
         * @return
         *     possible object is
         *     {@link Messaging.HornetqServer.JmsQueues }
         *     
         */
        public Messaging.HornetqServer.JmsQueues getJmsQueues() {
            return jmsQueues;
        }

        /**
         * Sets the value of the jmsQueues property.
         * 
         * @param value
         *     allowed object is
         *     {@link Messaging.HornetqServer.JmsQueues }
         *     
         */
        public void setJmsQueues(Messaging.HornetqServer.JmsQueues value) {
            this.jmsQueues = value;
        }

        /**
         * Gets the value of the jmsTopics property.
         * 
         * @return
         *     possible object is
         *     {@link Messaging.HornetqServer.JmsTopics }
         *     
         */
        public Messaging.HornetqServer.JmsTopics getJmsTopics() {
            return jmsTopics;
        }

        /**
         * Sets the value of the jmsTopics property.
         * 
         * @param value
         *     allowed object is
         *     {@link Messaging.HornetqServer.JmsTopics }
         *     
         */
        public void setJmsTopics(Messaging.HornetqServer.JmsTopics value) {
            this.jmsTopics = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="jms-queue" type="{http://www.example.org/JBossV6SnapshotSchema}JmsQueue" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "jmsQueue"
        })
        public static class JmsQueues {

            @XmlElement(name = "jms-queue", nillable = true)
            protected List<JmsQueue> jmsQueue;

            /**
             * Gets the value of the jmsQueue property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the jmsQueue property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getJmsQueue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JmsQueue }
             * 
             * 
             */
            public List<JmsQueue> getJmsQueue() {
                if (jmsQueue == null) {
                    jmsQueue = new ArrayList<JmsQueue>();
                }
                return this.jmsQueue;
            }

        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="jms-topic" type="{http://www.example.org/JBossV6SnapshotSchema}JmsTopic" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "jmsTopic"
        })
        public static class JmsTopics {

            @XmlElement(name = "jms-topic", nillable = true)
            protected List<JmsTopic> jmsTopic;

            /**
             * Gets the value of the jmsTopic property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the jmsTopic property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getJmsTopic().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JmsTopic }
             * 
             * 
             */
            public List<JmsTopic> getJmsTopic() {
                if (jmsTopic == null) {
                    jmsTopic = new ArrayList<JmsTopic>();
                }
                return this.jmsTopic;
            }

        }

    }

}
