//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for MessageDrivenBeanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageDrivenBeanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejb-refs" type="{http://www.example.org/JBossV6SnapshotSchema}EjbResType"/>
 *         &lt;element name="ejb-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activation-config-property" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="activation-config-property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="activation-config-property-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message-driven-destination" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="destination-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subscription-durability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ejb-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageDrivenBeanType", propOrder = {
    "ejbRefs",
    "ejbClass",
    "transactionType",
    "activationConfigProperty",
    "messageDrivenDestination"
})
public class MessageDrivenBeanType {

    @XmlElement(name = "ejb-refs", required = true)
    protected EjbResType ejbRefs;
    @XmlElement(name = "ejb-class", required = true)
    protected String ejbClass;
    @XmlElement(name = "transaction-type", required = true)
    protected String transactionType;
    @XmlElement(name = "activation-config-property")
    protected List<MessageDrivenBeanType.ActivationConfigProperty> activationConfigProperty;
    @XmlElement(name = "message-driven-destination")
    protected MessageDrivenBeanType.MessageDrivenDestination messageDrivenDestination;
    @XmlAttribute(name = "ejb-name")
    protected String ejbName;

    /**
     * Gets the value of the ejbRefs property.
     * 
     * @return
     *     possible object is
     *     {@link EjbResType }
     *     
     */
    public EjbResType getEjbRefs() {
        return ejbRefs;
    }

    /**
     * Sets the value of the ejbRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EjbResType }
     *     
     */
    public void setEjbRefs(EjbResType value) {
        this.ejbRefs = value;
    }

    /**
     * Gets the value of the ejbClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjbClass() {
        return ejbClass;
    }

    /**
     * Sets the value of the ejbClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjbClass(String value) {
        this.ejbClass = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the activationConfigProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activationConfigProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivationConfigProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageDrivenBeanType.ActivationConfigProperty }
     * 
     * 
     */
    public List<MessageDrivenBeanType.ActivationConfigProperty> getActivationConfigProperty() {
        if (activationConfigProperty == null) {
            activationConfigProperty = new ArrayList<MessageDrivenBeanType.ActivationConfigProperty>();
        }
        return this.activationConfigProperty;
    }

    /**
     * Gets the value of the messageDrivenDestination property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDrivenBeanType.MessageDrivenDestination }
     *     
     */
    public MessageDrivenBeanType.MessageDrivenDestination getMessageDrivenDestination() {
        return messageDrivenDestination;
    }

    /**
     * Sets the value of the messageDrivenDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDrivenBeanType.MessageDrivenDestination }
     *     
     */
    public void setMessageDrivenDestination(MessageDrivenBeanType.MessageDrivenDestination value) {
        this.messageDrivenDestination = value;
    }

    /**
     * Gets the value of the ejbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjbName() {
        return ejbName;
    }

    /**
     * Sets the value of the ejbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjbName(String value) {
        this.ejbName = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="activation-config-property-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="activation-config-property-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "activationConfigPropertyValue"
    })
    public static class ActivationConfigProperty {

        @XmlElement(name = "activation-config-property-value", required = true)
        protected String activationConfigPropertyValue;
        @XmlAttribute(name = "activation-config-property-name")
        protected String activationConfigPropertyName;

        /**
         * Gets the value of the activationConfigPropertyValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivationConfigPropertyValue() {
            return activationConfigPropertyValue;
        }

        /**
         * Sets the value of the activationConfigPropertyValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivationConfigPropertyValue(String value) {
            this.activationConfigPropertyValue = value;
        }

        /**
         * Gets the value of the activationConfigPropertyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActivationConfigPropertyName() {
            return activationConfigPropertyName;
        }

        /**
         * Sets the value of the activationConfigPropertyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActivationConfigPropertyName(String value) {
            this.activationConfigPropertyName = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="destination-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subscription-durability" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destinationType",
        "subscriptionDurability"
    })
    public static class MessageDrivenDestination {

        @XmlElement(name = "destination-type", required = true)
        protected String destinationType;
        @XmlElement(name = "subscription-durability", required = true)
        protected String subscriptionDurability;

        /**
         * Gets the value of the destinationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationType() {
            return destinationType;
        }

        /**
         * Sets the value of the destinationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationType(String value) {
            this.destinationType = value;
        }

        /**
         * Gets the value of the subscriptionDurability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriptionDurability() {
            return subscriptionDurability;
        }

        /**
         * Sets the value of the subscriptionDurability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriptionDurability(String value) {
            this.subscriptionDurability = value;
        }

    }

}
