//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.uc4.ara.feature.jbossv6.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.uc4.ara.feature.jbossv6.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebDDType }
     * 
     */
    public WebDDType createWebDDType() {
        return new WebDDType();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link RarSubsystemType }
     * 
     */
    public RarSubsystemType createRarSubsystemType() {
        return new RarSubsystemType();
    }

    /**
     * Create an instance of {@link Ejb3SubsystemType }
     * 
     */
    public Ejb3SubsystemType createEjb3SubsystemType() {
        return new Ejb3SubsystemType();
    }

    /**
     * Create an instance of {@link MessageDrivenBeanType }
     * 
     */
    public MessageDrivenBeanType createMessageDrivenBeanType() {
        return new MessageDrivenBeanType();
    }

    /**
     * Create an instance of {@link EjbResType.EjbRefs.EjbRef }
     * 
     */
    public EjbResType.EjbRefs.EjbRef createEjbResTypeEjbRefsEjbRef() {
        return new EjbResType.EjbRefs.EjbRef();
    }

    /**
     * Create an instance of {@link Host.Servers }
     * 
     */
    public Host.Servers createHostServers() {
        return new Host.Servers();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link SocketBindingGroup }
     * 
     */
    public SocketBindingGroup createSocketBindingGroup() {
        return new SocketBindingGroup();
    }

    /**
     * Create an instance of {@link ResourceAdapterType.ConfigProperties.ConfigProperty }
     * 
     */
    public ResourceAdapterType.ConfigProperties.ConfigProperty createResourceAdapterTypeConfigPropertiesConfigProperty() {
        return new ResourceAdapterType.ConfigProperties.ConfigProperty();
    }

    /**
     * Create an instance of {@link StandaloneDeployment }
     * 
     */
    public StandaloneDeployment createStandaloneDeployment() {
        return new StandaloneDeployment();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link EjbDDType.EntityBeans }
     * 
     */
    public EjbDDType.EntityBeans createEjbDDTypeEntityBeans() {
        return new EjbDDType.EntityBeans();
    }

    /**
     * Create an instance of {@link GeneralDataSources }
     * 
     */
    public GeneralDataSources createGeneralDataSources() {
        return new GeneralDataSources();
    }

    /**
     * Create an instance of {@link DomainServerInfo }
     * 
     */
    public DomainServerInfo createDomainServerInfo() {
        return new DomainServerInfo();
    }

    /**
     * Create an instance of {@link Messaging }
     * 
     */
    public Messaging createMessaging() {
        return new Messaging();
    }

    /**
     * Create an instance of {@link SarDDType.Mbeans.Mbean.Attribute }
     * 
     */
    public SarDDType.Mbeans.Mbean.Attribute createSarDDTypeMbeansMbeanAttribute() {
        return new SarDDType.Mbeans.Mbean.Attribute();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot }
     * 
     */
    public DomainServerSnapshot createDomainServerSnapshot() {
        return new DomainServerSnapshot();
    }

    /**
     * Create an instance of {@link SystemProperties }
     * 
     */
    public SystemProperties createSystemProperties() {
        return new SystemProperties();
    }

    /**
     * Create an instance of {@link ResourceRefType.EnvEntries }
     * 
     */
    public ResourceRefType.EnvEntries createResourceRefTypeEnvEntries() {
        return new ResourceRefType.EnvEntries();
    }

    /**
     * Create an instance of {@link MessageDrivenBeanType.ActivationConfigProperty }
     * 
     */
    public MessageDrivenBeanType.ActivationConfigProperty createMessageDrivenBeanTypeActivationConfigProperty() {
        return new MessageDrivenBeanType.ActivationConfigProperty();
    }

    /**
     * Create an instance of {@link EjbResType }
     * 
     */
    public EjbResType createEjbResType() {
        return new EjbResType();
    }

    /**
     * Create an instance of {@link DsSubsystemType.Datasource }
     * 
     */
    public DsSubsystemType.Datasource createDsSubsystemTypeDatasource() {
        return new DsSubsystemType.Datasource();
    }

    /**
     * Create an instance of {@link Messaging.HornetqServer }
     * 
     */
    public Messaging.HornetqServer createMessagingHornetqServer() {
        return new Messaging.HornetqServer();
    }

    /**
     * Create an instance of {@link ServerGroup.Deployments }
     * 
     */
    public ServerGroup.Deployments createServerGroupDeployments() {
        return new ServerGroup.Deployments();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot.Hosts }
     * 
     */
    public DomainServerSnapshot.Hosts createDomainServerSnapshotHosts() {
        return new DomainServerSnapshot.Hosts();
    }

    /**
     * Create an instance of {@link SocketBindingGroups }
     * 
     */
    public SocketBindingGroups createSocketBindingGroups() {
        return new SocketBindingGroups();
    }

    /**
     * Create an instance of {@link JdbcDrivers }
     * 
     */
    public JdbcDrivers createJdbcDrivers() {
        return new JdbcDrivers();
    }

    /**
     * Create an instance of {@link SessionBeanType }
     * 
     */
    public SessionBeanType createSessionBeanType() {
        return new SessionBeanType();
    }

    /**
     * Create an instance of {@link WebSubsystemType.Servlet }
     * 
     */
    public WebSubsystemType.Servlet createWebSubsystemTypeServlet() {
        return new WebSubsystemType.Servlet();
    }

    /**
     * Create an instance of {@link ResourceAdapterType.ConfigProperties }
     * 
     */
    public ResourceAdapterType.ConfigProperties createResourceAdapterTypeConfigProperties() {
        return new ResourceAdapterType.ConfigProperties();
    }

    /**
     * Create an instance of {@link ResourceAdapterType.ConnectionDefinitions }
     * 
     */
    public ResourceAdapterType.ConnectionDefinitions createResourceAdapterTypeConnectionDefinitions() {
        return new ResourceAdapterType.ConnectionDefinitions();
    }

    /**
     * Create an instance of {@link ResourceRefType.EnvEntries.EnvEntry }
     * 
     */
    public ResourceRefType.EnvEntries.EnvEntry createResourceRefTypeEnvEntriesEnvEntry() {
        return new ResourceRefType.EnvEntries.EnvEntry();
    }

    /**
     * Create an instance of {@link SarDDType.Mbeans.Mbean }
     * 
     */
    public SarDDType.Mbeans.Mbean createSarDDTypeMbeansMbean() {
        return new SarDDType.Mbeans.Mbean();
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link DsSubsystemType }
     * 
     */
    public DsSubsystemType createDsSubsystemType() {
        return new DsSubsystemType();
    }

    /**
     * Create an instance of {@link ServerGroupDeployment }
     * 
     */
    public ServerGroupDeployment createServerGroupDeployment() {
        return new ServerGroupDeployment();
    }

    /**
     * Create an instance of {@link WebSubsystemType }
     * 
     */
    public WebSubsystemType createWebSubsystemType() {
        return new WebSubsystemType();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot.Deployments }
     * 
     */
    public DomainServerSnapshot.Deployments createDomainServerSnapshotDeployments() {
        return new DomainServerSnapshot.Deployments();
    }

    /**
     * Create an instance of {@link SocketBindingGroup.SocketBindings }
     * 
     */
    public SocketBindingGroup.SocketBindings createSocketBindingGroupSocketBindings() {
        return new SocketBindingGroup.SocketBindings();
    }

    /**
     * Create an instance of {@link EjbResType.EjbLocalRefs }
     * 
     */
    public EjbResType.EjbLocalRefs createEjbResTypeEjbLocalRefs() {
        return new EjbResType.EjbLocalRefs();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link SubSystems }
     * 
     */
    public SubSystems createSubSystems() {
        return new SubSystems();
    }

    /**
     * Create an instance of {@link Datasources }
     * 
     */
    public Datasources createDatasources() {
        return new Datasources();
    }

    /**
     * Create an instance of {@link WebDDType.Servlets }
     * 
     */
    public WebDDType.Servlets createWebDDTypeServlets() {
        return new WebDDType.Servlets();
    }

    /**
     * Create an instance of {@link StandaloneServerSnapshot.Deployments }
     * 
     */
    public StandaloneServerSnapshot.Deployments createStandaloneServerSnapshotDeployments() {
        return new StandaloneServerSnapshot.Deployments();
    }

    /**
     * Create an instance of {@link JBossV6SnapshotType }
     * 
     */
    public JBossV6SnapshotType createJBossV6SnapshotType() {
        return new JBossV6SnapshotType();
    }

    /**
     * Create an instance of {@link ServerInfo }
     * 
     */
    public ServerInfo createServerInfo() {
        return new ServerInfo();
    }

    /**
     * Create an instance of {@link SubDeploymentType }
     * 
     */
    public SubDeploymentType createSubDeploymentType() {
        return new SubDeploymentType();
    }

    /**
     * Create an instance of {@link Extensions.Extension }
     * 
     */
    public Extensions.Extension createExtensionsExtension() {
        return new Extensions.Extension();
    }

    /**
     * Create an instance of {@link SarDDType.Mbeans }
     * 
     */
    public SarDDType.Mbeans createSarDDTypeMbeans() {
        return new SarDDType.Mbeans();
    }

    /**
     * Create an instance of {@link ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition }
     * 
     */
    public ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition createResourceAdapterTypeConnectionDefinitionsConnectionDefinition() {
        return new ResourceAdapterType.ConnectionDefinitions.ConnectionDefinition();
    }

    /**
     * Create an instance of {@link ResourceAdapterType }
     * 
     */
    public ResourceAdapterType createResourceAdapterType() {
        return new ResourceAdapterType();
    }

    /**
     * Create an instance of {@link ResourceRefType.ResourceRefs }
     * 
     */
    public ResourceRefType.ResourceRefs createResourceRefTypeResourceRefs() {
        return new ResourceRefType.ResourceRefs();
    }

    /**
     * Create an instance of {@link XaDataSources }
     * 
     */
    public XaDataSources createXaDataSources() {
        return new XaDataSources();
    }

    /**
     * Create an instance of {@link SarSubsystemType }
     * 
     */
    public SarSubsystemType createSarSubsystemType() {
        return new SarSubsystemType();
    }

    /**
     * Create an instance of {@link ServerGroup }
     * 
     */
    public ServerGroup createServerGroup() {
        return new ServerGroup();
    }

    /**
     * Create an instance of {@link FileGroupType }
     * 
     */
    public FileGroupType createFileGroupType() {
        return new FileGroupType();
    }

    /**
     * Create an instance of {@link Host }
     * 
     */
    public Host createHost() {
        return new Host();
    }

    /**
     * Create an instance of {@link SubsystemType }
     * 
     */
    public SubsystemType createSubsystemType() {
        return new SubsystemType();
    }

    /**
     * Create an instance of {@link Ejb3SubsystemType.Bean }
     * 
     */
    public Ejb3SubsystemType.Bean createEjb3SubsystemTypeBean() {
        return new Ejb3SubsystemType.Bean();
    }

    /**
     * Create an instance of {@link RarDDType.ResourceAdapters }
     * 
     */
    public RarDDType.ResourceAdapters createRarDDTypeResourceAdapters() {
        return new RarDDType.ResourceAdapters();
    }

    /**
     * Create an instance of {@link ResourceRefType }
     * 
     */
    public ResourceRefType createResourceRefType() {
        return new ResourceRefType();
    }

    /**
     * Create an instance of {@link SocketBindingGroup.SocketBindings.SocketBinding }
     * 
     */
    public SocketBindingGroup.SocketBindings.SocketBinding createSocketBindingGroupSocketBindingsSocketBinding() {
        return new SocketBindingGroup.SocketBindings.SocketBinding();
    }

    /**
     * Create an instance of {@link MessageDrivenBeanType.MessageDrivenDestination }
     * 
     */
    public MessageDrivenBeanType.MessageDrivenDestination createMessageDrivenBeanTypeMessageDrivenDestination() {
        return new MessageDrivenBeanType.MessageDrivenDestination();
    }

    /**
     * Create an instance of {@link ResourceRefType.ResourceEnvRefs.ResourceEnvRef }
     * 
     */
    public ResourceRefType.ResourceEnvRefs.ResourceEnvRef createResourceRefTypeResourceEnvRefsResourceEnvRef() {
        return new ResourceRefType.ResourceEnvRefs.ResourceEnvRef();
    }

    /**
     * Create an instance of {@link EjbDDType }
     * 
     */
    public EjbDDType createEjbDDType() {
        return new EjbDDType();
    }

    /**
     * Create an instance of {@link Interfaces }
     * 
     */
    public Interfaces createInterfaces() {
        return new Interfaces();
    }

    /**
     * Create an instance of {@link JmsQueue }
     * 
     */
    public JmsQueue createJmsQueue() {
        return new JmsQueue();
    }

    /**
     * Create an instance of {@link ApplicationRuntimeType }
     * 
     */
    public ApplicationRuntimeType createApplicationRuntimeType() {
        return new ApplicationRuntimeType();
    }

    /**
     * Create an instance of {@link GeneralDataSource }
     * 
     */
    public GeneralDataSource createGeneralDataSource() {
        return new GeneralDataSource();
    }

    /**
     * Create an instance of {@link ResourceRefType.ResourceEnvRefs }
     * 
     */
    public ResourceRefType.ResourceEnvRefs createResourceRefTypeResourceEnvRefs() {
        return new ResourceRefType.ResourceEnvRefs();
    }

    /**
     * Create an instance of {@link Messaging.HornetqServer.JmsTopics }
     * 
     */
    public Messaging.HornetqServer.JmsTopics createMessagingHornetqServerJmsTopics() {
        return new Messaging.HornetqServer.JmsTopics();
    }

    /**
     * Create an instance of {@link StandaloneServerSnapshot }
     * 
     */
    public StandaloneServerSnapshot createStandaloneServerSnapshot() {
        return new StandaloneServerSnapshot();
    }

    /**
     * Create an instance of {@link EjbResType.EjbLocalRefs.EjbLocalRef }
     * 
     */
    public EjbResType.EjbLocalRefs.EjbLocalRef createEjbResTypeEjbLocalRefsEjbLocalRef() {
        return new EjbResType.EjbLocalRefs.EjbLocalRef();
    }

    /**
     * Create an instance of {@link EjbDDType.MessageDrivenBeans }
     * 
     */
    public EjbDDType.MessageDrivenBeans createEjbDDTypeMessageDrivenBeans() {
        return new EjbDDType.MessageDrivenBeans();
    }

    /**
     * Create an instance of {@link EjbResType.EjbRefs }
     * 
     */
    public EjbResType.EjbRefs createEjbResTypeEjbRefs() {
        return new EjbResType.EjbRefs();
    }

    /**
     * Create an instance of {@link DeploymentDescriptorsType }
     * 
     */
    public DeploymentDescriptorsType createDeploymentDescriptorsType() {
        return new DeploymentDescriptorsType();
    }

    /**
     * Create an instance of {@link JdbcDriver }
     * 
     */
    public JdbcDriver createJdbcDriver() {
        return new JdbcDriver();
    }

    /**
     * Create an instance of {@link EntityBeanType }
     * 
     */
    public EntityBeanType createEntityBeanType() {
        return new EntityBeanType();
    }

    /**
     * Create an instance of {@link ResourceRefType.ResourceRefs.ResourceRef }
     * 
     */
    public ResourceRefType.ResourceRefs.ResourceRef createResourceRefTypeResourceRefsResourceRef() {
        return new ResourceRefType.ResourceRefs.ResourceRef();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot.ServerGroups }
     * 
     */
    public DomainServerSnapshot.ServerGroups createDomainServerSnapshotServerGroups() {
        return new DomainServerSnapshot.ServerGroups();
    }

    /**
     * Create an instance of {@link StandaloneServerInfo }
     * 
     */
    public StandaloneServerInfo createStandaloneServerInfo() {
        return new StandaloneServerInfo();
    }

    /**
     * Create an instance of {@link SubDeploymentType.Subdeployment }
     * 
     */
    public SubDeploymentType.Subdeployment createSubDeploymentTypeSubdeployment() {
        return new SubDeploymentType.Subdeployment();
    }

    /**
     * Create an instance of {@link ServerSnapshotType }
     * 
     */
    public ServerSnapshotType createServerSnapshotType() {
        return new ServerSnapshotType();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link ServletType }
     * 
     */
    public ServletType createServletType() {
        return new ServletType();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot.Deployments.Deployment }
     * 
     */
    public DomainServerSnapshot.Deployments.Deployment createDomainServerSnapshotDeploymentsDeployment() {
        return new DomainServerSnapshot.Deployments.Deployment();
    }

    /**
     * Create an instance of {@link SystemProperties.SystemProperty }
     * 
     */
    public SystemProperties.SystemProperty createSystemPropertiesSystemProperty() {
        return new SystemProperties.SystemProperty();
    }

    /**
     * Create an instance of {@link SarDDType }
     * 
     */
    public SarDDType createSarDDType() {
        return new SarDDType();
    }

    /**
     * Create an instance of {@link JmsTopic }
     * 
     */
    public JmsTopic createJmsTopic() {
        return new JmsTopic();
    }

    /**
     * Create an instance of {@link EjbDDType.SessionBeans }
     * 
     */
    public EjbDDType.SessionBeans createEjbDDTypeSessionBeans() {
        return new EjbDDType.SessionBeans();
    }

    /**
     * Create an instance of {@link XaDataSource }
     * 
     */
    public XaDataSource createXaDataSource() {
        return new XaDataSource();
    }

    /**
     * Create an instance of {@link SubSystems.Subsystem }
     * 
     */
    public SubSystems.Subsystem createSubSystemsSubsystem() {
        return new SubSystems.Subsystem();
    }

    /**
     * Create an instance of {@link RarDDType }
     * 
     */
    public RarDDType createRarDDType() {
        return new RarDDType();
    }

    /**
     * Create an instance of {@link Messaging.HornetqServer.JmsQueues }
     * 
     */
    public Messaging.HornetqServer.JmsQueues createMessagingHornetqServerJmsQueues() {
        return new Messaging.HornetqServer.JmsQueues();
    }

    /**
     * Create an instance of {@link DomainServerSnapshot.Profiles }
     * 
     */
    public DomainServerSnapshot.Profiles createDomainServerSnapshotProfiles() {
        return new DomainServerSnapshot.Profiles();
    }

}
