//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for SubDeploymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubDeploymentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subdeployment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deployment-descriptors" type="{http://www.example.org/JBossV6SnapshotSchema}DeploymentDescriptorsType"/>
 *                   &lt;element name="sub-systems" type="{http://www.example.org/JBossV6SnapshotSchema}SubsystemType"/>
 *                   &lt;element name="other-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
 *                   &lt;element name="class-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Subdeployments" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubDeploymentType", propOrder = {
    "subdeployment"
})
public class SubDeploymentType {

    protected List<SubDeploymentType.Subdeployment> subdeployment;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the subdeployment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subdeployment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubdeployment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubDeploymentType.Subdeployment }
     * 
     * 
     */
    public List<SubDeploymentType.Subdeployment> getSubdeployment() {
        if (subdeployment == null) {
            subdeployment = new ArrayList<SubDeploymentType.Subdeployment>();
        }
        return this.subdeployment;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Subdeployments";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="deployment-descriptors" type="{http://www.example.org/JBossV6SnapshotSchema}DeploymentDescriptorsType"/>
     *         &lt;element name="sub-systems" type="{http://www.example.org/JBossV6SnapshotSchema}SubsystemType"/>
     *         &lt;element name="other-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
     *         &lt;element name="class-files" type="{http://www.example.org/JBossV6SnapshotSchema}FileGroupType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deploymentDescriptors",
        "subSystems",
        "otherFiles",
        "classFiles"
    })
    public static class Subdeployment {

        @XmlElement(name = "deployment-descriptors", required = true)
        protected DeploymentDescriptorsType deploymentDescriptors;
        @XmlElement(name = "sub-systems", required = true)
        protected SubsystemType subSystems;
        @XmlElement(name = "other-files", required = true)
        protected FileGroupType otherFiles;
        @XmlElement(name = "class-files", required = true)
        protected FileGroupType classFiles;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the deploymentDescriptors property.
         * 
         * @return
         *     possible object is
         *     {@link DeploymentDescriptorsType }
         *     
         */
        public DeploymentDescriptorsType getDeploymentDescriptors() {
            return deploymentDescriptors;
        }

        /**
         * Sets the value of the deploymentDescriptors property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeploymentDescriptorsType }
         *     
         */
        public void setDeploymentDescriptors(DeploymentDescriptorsType value) {
            this.deploymentDescriptors = value;
        }

        /**
         * Gets the value of the subSystems property.
         * 
         * @return
         *     possible object is
         *     {@link SubsystemType }
         *     
         */
        public SubsystemType getSubSystems() {
            return subSystems;
        }

        /**
         * Sets the value of the subSystems property.
         * 
         * @param value
         *     allowed object is
         *     {@link SubsystemType }
         *     
         */
        public void setSubSystems(SubsystemType value) {
            this.subSystems = value;
        }

        /**
         * Gets the value of the otherFiles property.
         * 
         * @return
         *     possible object is
         *     {@link FileGroupType }
         *     
         */
        public FileGroupType getOtherFiles() {
            return otherFiles;
        }

        /**
         * Sets the value of the otherFiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileGroupType }
         *     
         */
        public void setOtherFiles(FileGroupType value) {
            this.otherFiles = value;
        }

        /**
         * Gets the value of the classFiles property.
         * 
         * @return
         *     possible object is
         *     {@link FileGroupType }
         *     
         */
        public FileGroupType getClassFiles() {
            return classFiles;
        }

        /**
         * Sets the value of the classFiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileGroupType }
         *     
         */
        public void setClassFiles(FileGroupType value) {
            this.classFiles = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
