//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.04 at 03:31:00 PM ICT 
//

package com.uc4.ara.feature.jbossv6.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for SubsystemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubsystemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejb3" type="{http://www.example.org/JBossV6SnapshotSchema}ejb3SubsystemType" minOccurs="0"/>
 *         &lt;element name="web" type="{http://www.example.org/JBossV6SnapshotSchema}webSubsystemType" minOccurs="0"/>
 *         &lt;element name="resource-adapters" type="{http://www.example.org/JBossV6SnapshotSchema}rarSubsystemType" minOccurs="0"/>
 *         &lt;element name="sar" type="{http://www.example.org/JBossV6SnapshotSchema}sarSubsystemType" minOccurs="0"/>
 *         &lt;element name="datasources" type="{http://www.example.org/JBossV6SnapshotSchema}dsSubsystemType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="Subsystem" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubsystemType", propOrder = {
    "ejb3",
    "web",
    "resourceAdapters",
    "sar",
    "datasources"
})
public class SubsystemType {

    protected Ejb3SubsystemType ejb3;
    protected WebSubsystemType web;
    @XmlElement(name = "resource-adapters")
    protected RarSubsystemType resourceAdapters;
    protected SarSubsystemType sar;
    protected DsSubsystemType datasources;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the ejb3 property.
     * 
     * @return
     *     possible object is
     *     {@link Ejb3SubsystemType }
     *     
     */
    public Ejb3SubsystemType getEjb3() {
        return ejb3;
    }

    /**
     * Sets the value of the ejb3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ejb3SubsystemType }
     *     
     */
    public void setEjb3(Ejb3SubsystemType value) {
        this.ejb3 = value;
    }

    /**
     * Gets the value of the web property.
     * 
     * @return
     *     possible object is
     *     {@link WebSubsystemType }
     *     
     */
    public WebSubsystemType getWeb() {
        return web;
    }

    /**
     * Sets the value of the web property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebSubsystemType }
     *     
     */
    public void setWeb(WebSubsystemType value) {
        this.web = value;
    }

    /**
     * Gets the value of the resourceAdapters property.
     * 
     * @return
     *     possible object is
     *     {@link RarSubsystemType }
     *     
     */
    public RarSubsystemType getResourceAdapters() {
        return resourceAdapters;
    }

    /**
     * Sets the value of the resourceAdapters property.
     * 
     * @param value
     *     allowed object is
     *     {@link RarSubsystemType }
     *     
     */
    public void setResourceAdapters(RarSubsystemType value) {
        this.resourceAdapters = value;
    }

    /**
     * Gets the value of the sar property.
     * 
     * @return
     *     possible object is
     *     {@link SarSubsystemType }
     *     
     */
    public SarSubsystemType getSar() {
        return sar;
    }

    /**
     * Sets the value of the sar property.
     * 
     * @param value
     *     allowed object is
     *     {@link SarSubsystemType }
     *     
     */
    public void setSar(SarSubsystemType value) {
        this.sar = value;
    }

    /**
     * Gets the value of the datasources property.
     * 
     * @return
     *     possible object is
     *     {@link DsSubsystemType }
     *     
     */
    public DsSubsystemType getDatasources() {
        return datasources;
    }

    /**
     * Sets the value of the datasources property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsSubsystemType }
     *     
     */
    public void setDatasources(DsSubsystemType value) {
        this.datasources = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Subsystem";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
